# Generated by Django 4.2.7 on 2025-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="clarity_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                ],
                default="BEGINNER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="preferred_learning_style",
            field=models.CharField(
                choices=[
                    ("VISUAL", "Visual"),
                    ("VERBAL", "Verbal"),
                    ("HANDS_ON", "Hands-on"),
                ],
                default="VERBAL",
                max_length=50,
            ),
        ),
    ]
