# Generated by Django 4.2.27 on 2025-12-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_initial"),
        ("mentorship", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
        migrations.RenameField(
            model_name="expertprofile",
            old_name="years_of_experience",
            new_name="years_experience",
        ),
        migrations.RemoveField(
            model_name="expertprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="expertprofile",
            name="expertise_areas",
        ),
        migrations.RemoveField(
            model_name="learnerprofile",
            name="current_role",
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="domains_of_expertise",
            field=models.JSONField(default=list, help_text="List of domains"),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="experience_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="role_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="learnerprofile",
            name="learning_goals",
            field=models.JSONField(default=list, help_text="List of goals"),
        ),
    ]
