FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Host 0.0.0.0 is needed for docker container to be accessible
CMD ["npm", "run", "dev", "--", "--host"]
