# Generated by Django 4.2.7 on 2025-12-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0002_knowledgemodule_scenario_learningpath_decisionnode"),
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentorship_sessions_as_expert",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="learner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorship_sessions_as_learner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live Session"),
                    ("ASYNC", "Async Message"),
                    ("AI_AVATAR", "AI Avatar"),
                ],
                default="AI_AVATAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="knowledge.knowledgemodule",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="personalization_context",
            field=models.JSONField(
                blank=True, default=dict, help_text="Context about learner goals/style"
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="knowledge.scenario",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="session_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="started_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MentorshipMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("learner", "Learner"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mentorship.mentorshipsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
