# Generated by Django 4.2.27 on 2025-12-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeInterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("date_conducted", models.DateTimeField(auto_now_add=True)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="interviews/videos/"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="interviews/audio/"
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                (
                    "gpt_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="Structured analysis from OpenAI",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
