# Generated by Django 4.2.27 on 2025-12-06 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeinterviewsession",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
